/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class delta_cion_Main */

#ifndef _Included_delta_cion_Main
#define _Included_delta_cion_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     delta_cion_Main
 * Method:    dc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_delta_cion_Main_dc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
